version: "3.1"
   
services:  
  web:
    container_name: elp_dja
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    container_name: elp_psq
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always

volumes: 
  postgresql:
