# Generated by Django 2.2.24 on 2021-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210721_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='product_new'),
        ),
    ]
